version: "3.8"
services:
  redpanda:
    image: redpandadata/redpanda:latest
    command: start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M
    ports:
      - "9092:9092"   # Kafka API (mapped to host)
      - "8082:8082"
    healthcheck:
      test: ["CMD", "rpk", "cluster", "id"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native client
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9001:9000"
    volumes:
      - minio-data:/data

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersetsecret
    depends_on:
      - clickhouse
    volumes:
      - ./superset:/app/superset_home

  init-clickhouse:
    image: clickhouse/clickhouse-server:latest
    depends_on:
      - clickhouse
    entrypoint: >
      bash -c "
        sleep 10 &&
        clickhouse-client --host clickhouse --query '
          CREATE TABLE IF NOT EXISTS events
          (
            event_time DateTime,
            user_id String,
            event_type String,
            video_id String,
            server_id String,
            payload String
          )
          ENGINE = MergeTree()
          ORDER BY (event_time, user_id);
        '
      "

volumes:
  clickhouse-data:
  minio-data: